name: "pr2"
# defines the observed joints and joints being randomised in the initial pose
joint_model_group_name: "right_arm_and_torso"
torso_joint_name: "torso_lift_joint"
frame_id: "map"
global_link_transform: "r_wrist_roll_link"
tip_to_gripper_offset:
  - 0.18
  - 0.0
  - 0.0
gripper_to_base_rot_offset:
  - 0
  - 0
  - 0
  - 1
base_cmd_topic: "/base_controller/command"
base_vel_rng: 0.2
base_rot_rng: 1.0
torso_vel_rng: 0.013
z_min: 0.2
z_max: 1.55
restricted_ws_z_min: 0.4
restricted_ws_z_max: 1.4
# max dist the ee plan is allowed to be from a feasible base plan
# Link Lengths: upper arm 400 mm, forearm 321 mm,wrist to gripper surface 120 - 200 mm
# https://tams.informatik.uni-hamburg.de/people/rockel/lectures/ROS_PR2_Introduction.pdf
arm_range: 0.5
gmm_base_offset: 0.02
kinematics_solver_timeout: 0.005
# pr2_navigation/pr2_navigation_config/move_base/move_base_params.yaml
robot_base_size_meters:
  - 0.65
  - 0.65
inflation_radius_ee: 0.40
# non-default joint values used in the simulator
initial_joint_values:
  bl_caster_rotation_joint: -0.000019
  br_caster_l_wheel_joint: -0.016590
  fl_caster_r_wheel_joint: 0.016280
  torso_lift_joint: 0.011498
  r_shoulder_lift_joint: 0.000448
  r_forearm_roll_joint: 0.000602
  r_gripper_l_finger_joint: 0.002207
  bl_caster_l_wheel_joint: -0.023353
  br_caster_r_wheel_joint: -0.015209
  fr_caster_l_wheel_joint: 0.026865
  head_pan_joint: 0.002320
  l_gripper_l_finger_joint: 0.002097
  r_upper_arm_roll_joint: -0.004287
  r_wrist_flex_joint: -0.466909
  bl_caster_r_wheel_joint: -0.023089
  fl_caster_l_wheel_joint: 0.008998
  fr_caster_r_wheel_joint: 0.029978
  head_tilt_joint: 0.224876
  r_shoulder_pan_joint: -0.000135
  r_elbow_flex_joint: -0.334197
  r_wrist_roll_joint: 0.000129
  # tucked arm in front: https://github.com/PR2/pr2_common_actions/blob/kinetic-devel/pr2_tuck_arms_action/src/pr2_tuck_arms_action/tuck_arms_main.py
  # NOTE: also hardcoded in RobotPR2::reset()
  l_shoulder_pan_joint: 0.06024
  l_shoulder_lift_joint: 1.248526
  l_upper_arm_roll_joint: 1.789070
  l_elbow_flex_joint: -1.50
  l_forearm_roll_joint: -1.7343417
  l_wrist_flex_joint: -0.0962141
  l_wrist_roll_joint: -0.0864407
gripper_collision_names:
  - 'pr2::r_gripper_r_finger_tip_link::r_gripper_r_finger_tip_link_collision'
  - 'pr2::r_gripper_l_finger_tip_link::r_gripper_l_finger_tip_link_collision'
  - 'pr2::r_gripper_r_finger_link::r_gripper_r_finger_link_collision'
  - 'pr2::r_gripper_l_finger_link::r_gripper_l_finger_link_collision'
  - 'pr2::r_wrist_roll_link::r_wrist_roll_link_fixed_joint_lump__r_gripper_palm_link_collision_1'
