name: "tiago"
joint_model_group_name: "arm_torso"
torso_joint_name: "torso_lift_joint"
frame_id: "map"
# webots: "wrist_ft_tool_link"
global_link_transform: "arm_tool_link"
tip_to_gripper_offset:
  - 0.205
  - 0.0
  - 0.0
gripper_to_base_rot_offset:
  - -0.706825
  - 0
  - 0
  - 0.707388
base_cmd_topic: "/mobile_base_controller/cmd_vel"
base_vel_rng: 0.2
base_rot_rng: 1.0
torso_vel_rng: 0.07
z_min: 0.2
z_max: 1.5
restricted_ws_z_min: 0.4
restricted_ws_z_max: 1.05
# max dist the ee plan is allowed to be from a feasible base plan
# https://pal-robotics.com/wp-content/uploads/2020/05/TIAGo-Datasheet.pdf
arm_range: 0.5
gmm_base_offset: 0.0
kinematics_solver_timeout: 0.005
# pmb2_robot/pmb2_description/urdf/base/footprint
robot_base_size_meters:
  - 0.525
inflation_radius_ee: 0.4
gripper_collision_names:
  - 'tiago::gripper_right_finger_link::gripper_right_finger_link_collision'
  - 'tiago::gripper_left_finger_link::gripper_left_finger_link_collision'